language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    - JWT_SECRET=supersecretkeyyoushouldnotcommittogithub

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script: vendor/bin/phpunit

